// Replace the value with your NFT contract address
// const CRYPTODEVS_NFT_CONTRACT_ADDRESS =
//   "YOUR_CRYPTODEVS_NFT_CONTRACT_ADDRESS_HERE";
const CRYPTODEVS_NFT_CONTRACT_ADDRESS =
  "0x52dC5936C3f039e7Af668280f6A7CFd46a64E0B4";

module.exports = { CRYPTODEVS_NFT_CONTRACT_ADDRESS };

